// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Teste.Impl.Context;

namespace Teste.Impl.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180123010438_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Teste.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnName("AADDED_DATE");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnName("BRAND")
                        .HasMaxLength(50);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnName("COLOR")
                        .HasMaxLength(30);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsNew")
                        .HasColumnName("IS_NEW");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("MODEL")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<decimal>("Price")
                        .HasColumnName("DECIMAL");

                    b.Property<int>("Year")
                        .HasColumnName("YEAR");

                    b.HasKey("Id");

                    b.ToTable("VEHICLE");
                });
#pragma warning restore 612, 618
        }
    }
}
